### ISSUE TITLE
Received same message many times

### ISSUE THREAD

**Issue by ttsshadow** [miwagner/ESP32-Arduino-CAN#14]
i try to run basic examples , and running well
but i have a little issue

why always received same message many times?
(message info and data is correct )
should send once only

any idea? thanks a lot!

**Comment by miwagner** [comment]
Hi,
is your construction as follows:
![CAN-BUS](https://user-images.githubusercontent.com/16373562/68084639-a74d5e80-fe38-11e9-92dd-f6c1f30eeac1.png)

Have you two bus participants and two 120Ohm resistor?

Best regards
