### ISSUE TITLE
esp hanging 

### ISSUE THREAD

**Issue by qubolino** [miwagner/ESP32-Arduino-CAN#32]
i just started using this library. i am using esp32 with HVD230 and a provided example. 

i already have a can bus working with a raspi and an arduino both mcp2515. raspi is running candump for me to see the traffic.

the esp32 is working fine at 500kbps for sone time: it receives the traffic, send frames. but at some point in time it stops working and only a hard reset makes it work again. is this a known issue?

**Comment by pswired** [comment]
If you lose connection to the CAN bus and the ESP32's transmissions go unacknowledged, I've found that the whole thing hangs. See https://github.com/miwagner/ESP32-Arduino-CAN/issues/27
