### ISSUE TITLE
Canbus frame rate

### ISSUE THREAD

**Issue by riodda** [miwagner/ESP32-Arduino-CAN#4]
Hi, i made a test with your library and a Wemos LOLIN32, i took the esp32can_basic sketch and i set the interval to 1 ms.
I falshed the sketch but i have a period of the frame of 7.6 ms with some serial output.
Disabling the serial output the period goes down to 3ms, but still 3 times the frame rate.
Is the ESP32 can known to be this slow ? With the Teensy 3.2 i archive 1ms depite the serial output.
Cheers.
![immagine](https://user-images.githubusercontent.com/13453063/44531219-83e53a80-a6f0-11e8-8310-417038ad8412.png)

**Comment by miwagner** [comment]
Hi,

what happens when you disable the the incomming CAN BUS Frames? Only sending is active.

Bye

Michael

**Comment by rutex0** [comment]
Try to change the timeout to 0 ms in the xQueueReceive() 

from:
 if (xQueueReceive(CAN_cfg.rx_queue, &rx_frame, 3 * portTICK_PERIOD_MS) == pdTRUE) {

to:
  if (xQueueReceive(CAN_cfg.rx_queue, &rx_frame, 0) == pdTRUE) {
