### ISSUE TITLE
Custom baud rate

### ISSUE THREAD

**Issue by Maxim-Issaev** [miwagner/ESP32-Arduino-CAN#41]
Hi, I am tired to read data from can. Baud rate in my car is 95238bps (Opel Astra h (2006)). How to config ESP32 to read? I tried to add CAN_SPEED_95KBPS = 95, but I have no success, I do it right? Or there are another methods to cofing ESP32. I use SN65HVD230.

**Comment by mister0wl** [comment]
Hey Maxim,
please view this thread for solution: https://github.com/miwagner/ESP32-Arduino-CAN/issues/38
