### ISSUE TITLE
can filter build error

### ISSUE THREAD

**Issue by riodda** [miwagner/ESP32-Arduino-CAN#5]
Hi i tryed to build the can filter example but i have and error:

Arduino:1.8.1 (Windows 7), TD: 1.35, Scheda:""WeMos" WiFi&Bluetooth Battery, 80MHz, 921600"

C:\Users\Dario\Documents\Arduino\libraries\ESP32-Arduino-CAN-master\examples\esp32can_filter\esp32can_filter.ino: In function 'void setup()':

esp32can_filter:19: error: 'CAN_filter_t' was not declared in this scope

   CAN_filter_t p_filter;

   ^

esp32can_filter:20: error: 'p_filter' was not declared in this scope

   p_filter.FM = Single_Mode;

   ^

esp32can_filter:20: error: 'Single_Mode' was not declared in this scope

   p_filter.FM = Single_Mode;

                 ^

esp32can_filter:31: error: 'class ESP32CAN' has no member named 'CANConfigFilter'

   ESP32Can.CANConfigFilter(&p_filter);

            ^

Più di una libreria trovata per "ESP32CAN.h"
Usata: C:\Users\Dario\Documents\Arduino\libraries\arduino-esp32-can-demo-master
Non usata: C:\Users\Dario\Documents\Arduino\libraries\ESP32-Arduino-CAN-master
Non usata: C:\Users\Dario\Documents\Arduino\libraries\ESP32-Arduino-CAN-master
Non usata: C:\Users\Dario\Documents\Arduino\libraries\ESP32-Arduino-CAN-master
Non usata: C:\Users\Dario\Documents\Arduino\libraries\ESP32-Arduino-CAN-master
exit status 1
'CAN_filter_t' was not declared in this scope

Questo report potrebbe essere più ricco di informazioni abilitando l'opzione
"Mostra un output dettagliato durante la compilazione"
in "File -> Impostazioni"

**Comment by miwagner** [comment]
Hi,

with the Arduino IDE 1.8.5 and 1.8.9 the example under Windows compile. 

Bye

Michael
