### ISSUE TITLE
NO OUTPUT CAN_MIRROR 

### ISSUE THREAD

**Issue by irfanafa** [miwagner/ESP32-Arduino-CAN#9]
Hi,
I have been trying to check the CAN_Mirror example. I used the arduino ide to flash the example into the ESP32 board. I dont get the desired output in the serial monitor. I would like to receive your advice for running the output.

Thankyou

**Comment by miwagner** [comment]
Hi,
is your construction as follows:
![CAN-BUS](https://user-images.githubusercontent.com/16373562/68084708-846f7a00-fe39-11e9-9c8c-66797dd2d771.png)

You need two bus participants and two 120Ohm resistor. The first participant sends messages to the ESP32 and sends them back.

Best regards
